# 1.1 Tensor

In [26]:
# 1. Import pytorch
import torch    

In [28]:
# 2. create a new 5x3 tensor
x = torch.empty(5, 3)
print(x)

tensor([[5.0445e-35, 0.0000e+00, 4.9888e-35],
        [0.0000e+00, 4.4842e-44, 0.0000e+00],
        [6.7262e-44, 0.0000e+00, 5.0574e-35],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 9.1084e-44]])


In [36]:
# 3. create a rand 5x3 tensor
x = torch.rand(5, 3)
print(x)

# to create a rand int 5x3 tensor
# x = torch.randint(low=0, high=10, size=(5, 3), dtype=torch.int)
# print(x)

tensor([[0.4263, 0.8481, 0.7796],
        [0.9051, 0.6010, 0.5277],
        [0.7984, 0.8451, 0.0692],
        [0.3139, 0.5813, 0.9895],
        [0.4326, 0.1387, 0.5032]])


In [37]:
# 4. create a 5x3 empty tensor, assign type as long
x = torch.empty(5, 3, dtype=torch.long)
print(x)

tensor([[          109497944, 4605814430377181184, 4605197204385169408],
        [4606327765405270016, 4603588379966177280, 4602928304696066048],
        [4605366518975299584, 4605787489657946112, 4589652230608519168],
        [4599325730688466944, 4603411195922219008, 4607087970321694720],
        [4601464422538412032, 4594164866847080448, 4602707490763702272]])


In [38]:
# 5. create a tensor from a given array
x = torch.tensor([5,3])
print(x)

tensor([5, 3])


In [39]:
# 6. create a 5x3 unit tensor, type is double
x = torch.ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [41]:
# 7. create a tensor from a given tensor with the same dim, and redefine the type as float
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.1899, 0.8358, 0.2715],
        [0.5146, 0.4080, 0.1280],
        [0.7226, 0.9257, 0.5394],
        [0.6322, 0.2115, 0.0198],
        [0.9839, 0.9529, 0.6378]])


In [44]:
# 8. print a tensor's dim
print(x.size())

torch.Size([5, 3])


In [49]:
# 9.sum two tensor
y = torch.rand_like(x)
x = y + x
print(x)

# method 2 - use torch.add
x = torch.add(x, y)
print(x)

# method 3 - use result
result = torch.empty_like(x)    
torch.add(x, y, out= result)
print(result)
# method 4 - in place operation
x.add_(y)
print(x)


tensor([[5.2302, 4.4630, 5.9696],
        [3.8187, 4.3267, 4.7834],
        [6.4447, 7.2001, 4.8216],
        [6.6190, 7.1720, 2.7113],
        [7.5886, 5.3152, 4.5408]])
tensor([[5.9354, 4.8969, 6.9626],
        [3.8614, 4.7555, 5.2285],
        [7.1472, 8.1632, 5.4949],
        [6.7404, 7.9783, 3.4300],
        [8.5711, 6.2545, 4.7069]])
tensor([[6.6407, 5.3308, 7.9556],
        [3.9042, 5.1843, 5.6735],
        [7.8497, 9.1263, 6.1682],
        [6.8619, 8.7846, 4.1487],
        [9.5535, 7.1938, 4.8731]])
tensor([[6.6407, 5.3308, 7.9556],
        [3.9042, 5.1843, 5.6735],
        [7.8497, 9.1263, 6.1682],
        [6.8619, 8.7846, 4.1487],
        [9.5535, 7.1938, 4.8731]])


In [50]:
# 10. print a tensor's first col
print(x[:,1])

tensor([5.3308, 5.1843, 9.1263, 8.7846, 7.1938])


In [53]:
# 11. reshape a 4x4 tensor to a 1d array tensor
y = x.flatten()
print(y)

y = x.reshape([-1])
print(y)

tensor([6.6407, 5.3308, 7.9556, 3.9042, 5.1843, 5.6735, 7.8497, 9.1263, 6.1682,
        6.8619, 8.7846, 4.1487, 9.5535, 7.1938, 4.8731])
tensor([6.6407, 5.3308, 7.9556, 3.9042, 5.1843, 5.6735, 7.8497, 9.1263, 6.1682,
        6.8619, 8.7846, 4.1487, 9.5535, 7.1938, 4.8731])


In [55]:
# 12. reshape a 4x4 tensor to a 2x8 tensor
x = torch.rand(4, 4)
x = x.reshape([2, -1])
print(x)


tensor([[0.9929, 0.8525, 0.0235, 0.5199, 0.8238, 0.6393, 0.5964, 0.1946],
        [0.6378, 0.3775, 0.1404, 0.2933, 0.2193, 0.0268, 0.7985, 0.4267]])


In [65]:
# 13. extract the number(item) from the tensor
x.size()

print(x[1,3].item())

0.2932972311973572
